### ISSUE TITLE
Dead

### ISSUE THREAD

**Issue by pvorb** [pgte/alfred#18]
I think this project is dead. What about continuing it on our own?

**Comment by pgte** [comment]
You are free to fork away. Nowadays I'd take a completely different
path to this anyway :)

No dia 04/02/2012, às 20:13, Paul Vorbach
reply@reply.github.com
escreveu:

**Comment by sergioramos** [comment]
Yes, from the little I saw, I think it should be rewritten. But something like that takes time...

I still think we need a in-process db.

**Comment by pgte** [comment]
Yes we do, but I'd do it using a leveldb binding and build from there.

On Feb 4, 2012, at 8:41 PM, "Sérgio Ramos"
reply@reply.github.com
wrote:

**Comment by pvorb** [comment]
Have there been any problems, that you couldn't solve with plain JavaScript objects or what are the reasons why you recommend a binding? Wouldn't it be cleaner to build it entirely in JavaScript without any dependencies? Otherwise you could also use redis/mongodb/couchdb/…

**Comment by pgte** [comment]
Redis/mongodb/couchdb are all services that are out of process.
Leveldb is an embeddable db engine that is battle-hardened. If anyone
is to take a proj like this seriously and not treat it like another
experiment on node, it has to be based on something ppl trust. Ppl
take their data seriously...

No dia 05/02/2012, às 00:12, Paul Vorbach
reply@reply.github.com
escreveu:

**Comment by pvorb** [comment]
That's not an easy decision. I don't think that I am the right person for this, because I'm not that experienced in C++.

Maybe I'll do some experiments with a plain JS implementation on my own.

**Comment by pgte** [comment]
Everyone should do that type of experiment, really learned a lot bout node.
Anyway there already is a good binding for leveldb somewhere I remember reading.

No dia 05/02/2012, às 12:02, Paul Vorbach
reply@reply.github.com
escreveu:

**Comment by pvorb** [comment]
Maybe [creationix/node-leveldb](https://github.com/creationix/node-leveldb)?

**Comment by pgte** [comment]
That one is actually not finished, there's  a fork of that one, I'll
check when back to pc.

No dia 05/02/2012, às 13:27, Paul Vorbach
reply@reply.github.com
escreveu:

**Comment by pgte** [comment]
This one: https://github.com/my8bird/node-leveldb

**Comment by sergeyksv** [comment]
Well, we choose alfred for one of our project and with some bug fixes it finally start to work stable enough. Though alfred is not ideal it has closest set of functions we looking for in-process key/value store. So will stick on it for some time.
