### ISSUE TITLE
How alfred keep sync between multi-processes

### ISSUE THREAD

**Issue by guileen** [pgte/alfred#4]
As I know that alfred is in process db, so each process handle an db instance, so how to keep these databases sync?

And unlike mongodb, multi-server and multi-process can connect to 1 master database, every alfred is stand alone, do you means that the architecture of a website should mix up the web and database, and if we need sharding then we should be shard by pairs of web and database.

It's a question but I don't know where to ask.

**Comment by pgte** [comment]
Alfred is only suited for single-process apps.
